web:
  build: .
  command: sh -c 'python3 -u app.py > /nmo_swc/log/app.log 2>&1'
  #command: sh -c 'Xvfb :99 -ac & DISPLAY=:99 python3 -u app.py > /nmo_swc/log/app.log 2>&1'
  ports:
    - "5151:5000"
  volumes:
    - .:/nmo_swc
    - ./Source-Version:/nmo_swc/Source-Version
    - ./output_Final:/nmo_swc/output_Final
    - ./output:/nmo_swc/output
    - ./output_zips:/nmo_swc/output_zips
    - ./output_Tag:/nmo_swc/output_Tag
    - ./output_Tag_zips:/nmo_swc/output_Tag_zips
    #- ./neutube_File:/nmo_swc/neutube_File
    #- /tmp/.X11-unix:/tmp/.X11-unix 
  environment:
    - DISPLAY=:99  # Set the DISPLAY environment variable
    - COMPOSE_HTTP_TIMEOUT=120
  user: root
  mem_limit: 2g
  ulimits:
      nofile: #devices:
        soft: 100000 #- /dev/dri:/dev/dri
        hard: 100000
